name: deploy-cron
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  vercel:
    runs-on: ubuntu-latest
    name: 'Deploy front-end'

    steps:
      - uses: actions/checkout@v2
      - name: 'Deploy to Vercel'
        run: npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
